### PR TITLE
trivial_stat example for Java

### PR DESCRIPTION
**Pull request by ytobe**
I created an example of trivial_stat for Java which works on jubatus 0.9.0 .

### CODE REVIEW

**Comment by kmaehashi** [comment]
* This exmaple could not be run with default java on Ubuntu 12.04 (openjdk-6).  Worked fine with openjdk-7.  Could you please add README and describe the requirements?

```
Caused by: java.lang.UnsupportedClassVersionError: com/opencsv/CSVReader : Unsupported major.minor version 51.0
``

* Please add exec permission to `run.sh` like other examples.

**Comment by kmaehashi** [comment]
:+1: LGTM except for comments above.

**Comment by kmaehashi** [comment]
One more thing:

* Please add `.gitignore` to ignore `target/` directory.

**Comment by ytobe** [comment]
Thanks for your review.
I dealt with them.

**Comment by kmaehashi** [comment]
:+1:

**Pull request merged**
