### PR TITLE
fix twitter_streaming_location for python 3 support

### PR DESCRIPTION
**Pull request by kmaehashi**
Refs #41

### CODE REVIEW

**Comment by rimms** [comment]
I tested this patch.

I faced the followings error.
```
Traceback (most recent call last):
  File "./train.py", line 142, in <module>
    train_tweets()
  File "./train.py", line 138, in train_tweets
    stream.filter(locations=request_coordinates)
  File "/home/rimms/.pyenv/versions/3.4.3/lib/python3.4/site-packages/tweepy/streaming.py", line 430, in filter
    self._start(async)
  File "/home/rimms/.pyenv/versions/3.4.3/lib/python3.4/site-packages/tweepy/streaming.py", line 346, in _start
    self._run()
  File "/home/rimms/.pyenv/versions/3.4.3/lib/python3.4/site-packages/tweepy/streaming.py", line 286, in _run
    raise exception
  File "/home/rimms/.pyenv/versions/3.4.3/lib/python3.4/site-packages/tweepy/streaming.py", line 255, in _run
    self._read_loop(resp)
  File "/home/rimms/.pyenv/versions/3.4.3/lib/python3.4/site-packages/tweepy/streaming.py", line 298, in _read_loop
    line = buf.read_line().strip()
  File "/home/rimms/.pyenv/versions/3.4.3/lib/python3.4/site-packages/tweepy/streaming.py", line 171, in read_line
    self._buffer += self._stream.read(self._chunk_size)
TypeError: Can't convert 'bytes' object to str implicitl
```

**Comment by kmaehashi** [comment]
I confirmed this with tweepy 3.4.0.  It was working with tweepy 3.3.0.

**Comment by kmaehashi** [comment]
Hmm, seems like an issue in tweepy library. https://github.com/tweepy/tweepy/issues/615

**Comment by kmaehashi** [comment]
It seems that the latest tweepy library fixed the Py3 issue.
I set the milestone to 0.9.1.

**Comment by rimms** [comment]
I tested ``2.7.9`` and ``3.5.1`` .
It works correctly.

**Pull request merged**
